# Generated by Django 4.0.1 on 2022-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAdministracion_InsumosComputacionales',
            fields=[
                ('numero_insumo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_adquisicion', models.DateField()),
                ('marca', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AppAdministracion_InsumosOficina',
            fields=[
                ('nro_articulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=25)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AppAdministracion_Usuarios',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40, unique=True)),
                ('email', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('perfil', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AppAdministracion_Vehiculos',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('numero_chasis', models.CharField(max_length=17, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=10)),
                ('ultima_revision', models.DateField()),
                ('proxima_revision', models.DateField()),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
    ]
